### ISSUE TITLE
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by ChenDuan** [nuxt/koa#61]
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In G:\nuxt-learn\node_modules\backpack-core\babel.js
    at createDescriptor (G:\nuxt-learn\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at items.map (G:\nuxt-learn\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (G:\nuxt-learn\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (G:\nuxt-learn\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at passPerPreset (G:\nuxt-learn\node_modules\@babel\core\lib\config\config-descriptors.js:58:96)
    at cachedFunction (G:\nuxt-learn\node_modules\@babel\core\lib\config\caching.js:33:19)
    at presets.presets (G:\nuxt-learn\node_modules\@babel\core\lib\config\config-descriptors.js:29:84)
    at mergeChainOpts (G:\nuxt-learn\node_modules\@babel\core\lib\config\config-chain.js:320:26)
    at G:\nuxt-learn\node_modules\@babel\core\lib\config\config-chain.js:283:7

module.js:550
    throw err;
    ^

Error: Cannot find module 'G:\nuxt-learn\build\main.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/koa-template/issues/c40">#c40</a>)</em></sub></div>

**Comment by 9yues** [comment]
请问你解决了吗，我也遇到同样的问题了

**Comment by soluteli** [comment]
> 请问你解决了吗，我也遇到同样的问题了

参照这个
https://github.com/nuxt-community/koa-template/issues/44#issuecomment-460150842

**Comment by w4ctech** [comment]
解决方法：

1.  修改``package.json``的配置。将``devDependencies``项修改为
```javascript
 "devDependencies": {
    "babel-eslint": "^10.0.1",
    "backpack-core": "^0.8.3",
    "eslint": "^5.16.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-html": "^5.0.3",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-node": "^4.2.2",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "nodemon": "^1.11.0",
    "scmp": "^2.0.0"
  }
```
2. 修改``Nuxt.config.js`` 的配置，关闭eslint的检查
```javascript
  build: {
    /*
     ** Run ESLINT on save （关闭eslint的检查）
     */
    // extend(config, ctx) {
    //   if (ctx.isClient) {
    //     config.module.rules.push({
    //       enforce: 'pre',
    //       test: /\.(js|vue)$/,
    //       loader: 'eslint-loader',
    //       exclude: /(node_modules)/
    //     })
    //   }
    // }
  }
```
删除``node_modules``包。重新``npm install`` ``npm run dev ``
